# Generated by Django 3.0.4 on 2020-03-05 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator_target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=100)),
                ('target_type', models.CharField(choices=[('Numbers', 'Numbers'), ('Percentage', 'Percentage')], default='Numbers', max_length=50)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imihigo.Indicator')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('item_target', models.CharField(max_length=50)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imihigo.Indicator')),
            ],
        ),
        migrations.CreateModel(
            name='Pillsector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(choices=[('ECONOMIC TRANSFORMATION PILLAR ', 'ECONOMIC TRANSFORMATION PILLAR '), ('SOCIAL  TRANSFORMATION PILLAR', 'SOCIAL  TRANSFORMATION PILLAR'), ('TRANSFORMATIONAL GOVERNANCE', 'TRANSFORMATIONAL GOVERNANCE')], max_length=80)),
                ('sector', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Raporo_yimihigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_quater', models.CharField(choices=[('Q1', 'Quater 1'), ('Q2', 'Quater 2'), ('Q3', 'Quater 3'), ('Q4', 'Quater 4')], max_length=50)),
                ('current_status', models.PositiveIntegerField()),
                ('comments', models.TextField()),
                ('items_to_report_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imihigo.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='measurement',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='imihigo.Unit'),
        ),
        migrations.AddField(
            model_name='item',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imihigo.Pillsector'),
        ),
        migrations.AddField(
            model_name='item',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imihigo.Indicator_target'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imihigo.Pillsector'),
        ),
    ]
