# Generated by Django 3.0.4 on 2020-03-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imihigo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_target',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='raporo_yimihigo',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
