# Generated by Django 3.0.4 on 2020-03-05 11:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('imihigo', '0002_auto_20200305_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='time',
            field=models.DateField(default=datetime.datetime(2020, 3, 5, 11, 6, 37, 455952, tzinfo=utc)),
        ),
    ]
