# Generated by Django 3.0.4 on 2020-03-05 10:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('imihigo', '0003_indicator_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='time',
            field=models.DateField(default=datetime.datetime(2020, 3, 5, 10, 4, 52, 621578, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.CharField(help_text='Example  Banana .. etc', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_target',
            field=models.PositiveIntegerField(help_text='Example   120,900  ect'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='target',
        ),
        migrations.AddField(
            model_name='item',
            name='target',
            field=models.ManyToManyField(to='imihigo.Indicator_target'),
        ),
    ]
