# Generated by Django 3.0.4 on 2020-03-05 10:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('imihigo', '0004_auto_20200305_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='time',
            field=models.DateField(default=datetime.datetime(2020, 3, 5, 10, 23, 9, 919959, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='indicator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='imihigo.Indicator'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='target',
        ),
        migrations.AddField(
            model_name='item',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='imihigo.Indicator_target'),
            preserve_default=False,
        ),
    ]
